# https://artifacthub.io/packages/helm/prometheus-community/prometheus
alertmanager:
  enabled: false
alertmanagerFiles:
  alertmanager.yml: ""

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
