{{- if eq .Values.ecto.baseKey.hardcoded true -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ecto.baseKey.secret.name }}
type: Opaque
data:
  secret_key: {{ default "IFvLZpso9kLZ2WezKuG6sGAbxU8ljmoYCg+Ei1yNeqLczKVtTCUOhnTKEMprLBn1" .Values.ecto.baseKey.value }}
immutable: true
{{- end -}}
